# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tryme' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for trim
   pod 'BLink2', :path => '../../BLink2'


end
